import { createElement } from 'lwc';
import UpdateRecordLightningUI_API from 'c/updateRecordLightningUI_API';

describe('c-update-record-lightning-u-i-api', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-update-record-lightning-u-i-api', {
            is: UpdateRecordLightningUI_API
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});